// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateClientProfile(ctx context.Context, arg CreateClientProfileParams) (uuid.UUID, error)
	DeleteCreateClientProfile(ctx context.Context, id uuid.UUID) error
	GetClientProfile(ctx context.Context, id uuid.UUID) (ClientProfile, error)
}

var _ Querier = (*Queries)(nil)
