// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Odvin/go-accounting-service/db/sqlc (interfaces: Store)
//
// Generated by this command:
//
//	mockgen -package mockdb -destination db/mock/store.go github.com/Odvin/go-accounting-service/db/sqlc Store
//
// Package mockdb is a generated GoMock package.
package mockdb

import (
	context "context"
	reflect "reflect"

	db "github.com/Odvin/go-accounting-service/db/sqlc"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// CreateClientProfile mocks base method.
func (m *MockStore) CreateClientProfile(arg0 context.Context, arg1 db.CreateClientProfileParams) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateClientProfile", arg0, arg1)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateClientProfile indicates an expected call of CreateClientProfile.
func (mr *MockStoreMockRecorder) CreateClientProfile(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateClientProfile", reflect.TypeOf((*MockStore)(nil).CreateClientProfile), arg0, arg1)
}

// DeleteCreateClientProfile mocks base method.
func (m *MockStore) DeleteCreateClientProfile(arg0 context.Context, arg1 uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCreateClientProfile", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCreateClientProfile indicates an expected call of DeleteCreateClientProfile.
func (mr *MockStoreMockRecorder) DeleteCreateClientProfile(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCreateClientProfile", reflect.TypeOf((*MockStore)(nil).DeleteCreateClientProfile), arg0, arg1)
}

// GetClientProfile mocks base method.
func (m *MockStore) GetClientProfile(arg0 context.Context, arg1 uuid.UUID) (db.ClientProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetClientProfile", arg0, arg1)
	ret0, _ := ret[0].(db.ClientProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetClientProfile indicates an expected call of GetClientProfile.
func (mr *MockStoreMockRecorder) GetClientProfile(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClientProfile", reflect.TypeOf((*MockStore)(nil).GetClientProfile), arg0, arg1)
}
